name: Build Vue
on: 
  push:
    branches: [ "production" ]
  pull_request:
    branches: [ "production" ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'sohepalslamat'
        reponame: 'vue-sfp-services'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
