name: Build Vue
on: [push]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: sh ./deploy.sh
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
        username: 'sohepalslamat'
        reponame: 'vue-sfp-services'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
